import { NextRequest, NextResponse } from 'next/server'
import OpenAI from 'openai'
import { adminDb } from '@/lib/firebase-admin'

// ✅ Removed module-level OpenAI init — moved inside POST to avoid build crash
const DETECTOR_PROMPT_ID = 'pmpt_69a3e4f87a80819085db0e4788a6fccc08d5c2d98eb0c9da'
const DETECTOR_PROMPT_VERSION = '5'

export const runtime = 'nodejs'   // ✅ Force Node runtime — required for firebase-admin

export async function POST(req: NextRequest) {
    try {
        // ✅ Lazy init — only runs at request time, not at build time
        const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY })

        const body = await req.json()
        const {
            essay_content,
            studentId,
            studentName,
            essayTitle,
            topicName,
        } = body

        if (!essay_content?.trim()) {
            return NextResponse.json(
                { error: 'Essay content is required.' },
                { status: 400 }
            )
        }

        const response = await (openai as any).responses.create({
            prompt: {
                id: DETECTOR_PROMPT_ID,
                version: DETECTOR_PROMPT_VERSION,
                variables: { essay_content },
            },
        })

        const raw: string =
            response.output_text ??
            response.choices?.[0]?.message?.content ??
            ''

        const isAi = /ai[\s-]?content/i.test(raw) || /generated by ai/i.test(raw)
        const verdict = isAi ? 'ai' : 'human'

        if (isAi && studentId) {
            try {
                await adminDb.collection('ai_detection_logs').add({
                    studentId,
                    studentName: studentName || 'Unknown',
                    essayTitle: essayTitle || 'Untitled',
                    topicName: topicName || 'Unknown Topic',
                    verdict,
                    detectedAt: new Date(),
                    excerpt: essay_content.trim().slice(0, 200),
                    fullText: essay_content.trim(),
                })
            } catch (logErr) {
                console.error('Failed to save AI detection log:', logErr)
            }
        }

        return NextResponse.json({ verdict, raw })

    } catch (err: any) {
        console.error('AI Detector error:', err)
        return NextResponse.json(
            { error: err?.message || 'AI detection failed. Please try again.' },
            { status: 500 }
        )
    }
}
